# Generated by Django 6.1.1 on 2026-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('location', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], max_length=50)),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('0-1 years', '0-1 years'), ('1-3 years', '1-3 years'), ('3-5 years', '3-5 years'), ('3+ years', '3+ years')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
