# Generated by Django 6.1.1 on 2026-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
