# Generated by Django 6.1.1 on 2026-10-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resumeanalysis_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
